version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - localstack-data:/var/lib/localstack

  terraform:
    image: hashicorp/terraform:1.7.5
    working_dir: /workspace
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ENDPOINT_URL_S3=http://localstack:4566
      - AWS_S3_USE_PATH_STYLE=true
    volumes:
      - ./:/workspace

volumes:
  localstack-data:
